### PR TITLE
Fix stacktraces for overwritten properties and methods

### LINKED ISSUE #659: stack trace wrong for overridden properties
let's say I use the following assertion:

```js
expect(true).to.be.undefined;
```

I get the following error with the expected stack trace:

```
AssertionError: expected true to be undefined
 at Context.<anonymous> (test/test.js:18:25)
```

---

If I overwrite the `undefined` property like this:

```js
Assertion.overwriteProperty('undefined', function(_super) {
  return function() {
    _super.call(this);
  };
});
```

I'm getting the following error with an extended stack trace:

```
AssertionError: expected true to be undefined
 at Assertion.<anonymous> (src/chai-files.js:52:12)
 at Assertion.Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
 at Context.<anonymous> (test/test.js:18:25)
```

---

If I overwrite the `undefined` property like this:

```js
Assertion.overwriteProperty('undefined', function(_super) {
  return function() {
    this.assert(false, 'foo', 'bar');
  };
});
```

I'm getting the following error with a missing stack trace:

```
AssertionError: foo
```

### PR DESCRIPTION
**Pull request by Turbo87**
This PR resolves #659 

Since testing overwritten properties/methods doesn't seems to be possible at the moment I tested this manually and it seems to work now. It would be good if this could be verified by someone else before merging though!

/cc @keithamus

### CODE REVIEW

**Comment by Turbo87** [comment]
@keithamus any comments on this?

File: lib/chai/utils/addChainableMethod.js [hunk 1]
```diff
@@ -79,7 +78,7 @@ module.exports = function (ctx, name, method, chainingBehavior) {
 
         var assert = function assert() {
           var old_ssfi = flag(this, 'ssfi');
-          if (old_ssfi && config.includeStack === false)
+          if (old_ssfi)
```
Comment (keithamus) [inline lib/chai/utils/addChainableMethod.js]: Could you please explain why you've removed the `config.includeStack` part here?

File: lib/chai/utils/addProperty.js [hunk 2]
```diff
@@ -40,8 +39,9 @@ module.exports = function (ctx, name, getter) {
 
   Object.defineProperty(ctx, name,
     { get: function addProperty() {
+        var keep_ssfi = flag(this, 'keep_ssfi');
```
Comment (keithamus) [inline lib/chai/utils/addProperty.js]: Could you also explain why we need the `keep_ssfi` flag. As far as I can see it is used to to override ssfi when we chain on properties - is this right?

File: lib/chai/utils/addChainableMethod.js (hunk 1 above)
Comment (Turbo87) [inline lib/chai/utils/addChainableMethod.js]: That flag is already checked in the assert() method and checking it here has no real benefit aside from making the logic more complicated

File: lib/chai/utils/addProperty.js (hunk 2 above)
Comment (Turbo87) [inline lib/chai/utils/addProperty.js]: imagine expect(true).to.be.false with false overwritten:

- expect sets ssfi
- to overwrites ssfi
- be overwrites ssfi
- custom false overwrites ssfi
- _super false overwrites ssfi

but actually that last part shouldn't happen because you don't want the _super in the stack trace. setting keep_ssfi during the _super prevents that from happening.

**Comment by keithamus** [comment]
LGTM, I'd like @lucasfcosta to review this one also though.

**Comment by Turbo87** [comment]
Sure, it needs a bit of brain twisting to understand what's going on :wink:

File: lib/chai/utils/overwriteMethod.js [hunk 3]
```diff
@@ -46,7 +48,15 @@ module.exports = function (ctx, name, method) {
     _super = _method;
 
   ctx[name] = function () {
+    var keep_ssfi = flag(this, 'keep_ssfi');
+    var old_ssfi = flag(this, 'ssfi');
+    if (!keep_ssfi && old_ssfi)
+      flag(this, 'ssfi', ctx[name]);
+
+    flag(this, 'keep_ssfi', true);
```
Comment (lucasfcosta) [inline lib/chai/utils/overwriteMethod.js]: Hi @Turbo87, I just want to confirm I understood the whole thing here:

Whenever you overwrite a method you set `keep_ssfi` to true before calling `_super` so you won't get that call on the stack due to those checks you added to `addMethod`, `addChainableMethod` and `addProperty`, am I right?

Comment (Turbo87) [inline lib/chai/utils/overwriteMethod.js]: correct

File: lib/chai/utils/addProperty.js (hunk 2 above)
Comment (lucasfcosta) [inline lib/chai/utils/addProperty.js]: Shouldn't we test if `_super` is really in the stack trace when we've got properties/methods overwritten?
What do you guys think about this?

Tests are okay, now, but maybe we could have this too.

**Comment by lucasfcosta** [comment]
Hello everyone, first of all, thanks for the PR @Turbo87, great job here :smile: !

I needed to pay a lot of attention to really understand how to handle the Stack Trace properly, but I think I've got it. This is looking good, in general, anyway, I just added two notes to the code just to ensure we're going in the right direction here.

My two notes are [here](https://github.com/chaijs/chai/pull/661#discussion_r58314409) and [here](https://github.com/chaijs/chai/pull/661#discussion_r58314662).

File: lib/chai/utils/addProperty.js (hunk 2 above)
Comment (keithamus) [inline lib/chai/utils/addProperty.js]: Yup, great idea :+1: :100:

Comment (Turbo87) [inline lib/chai/utils/addProperty.js]: @lucasfcosta but sure I understand what you meant?

Comment (lucasfcosta) [inline lib/chai/utils/addProperty.js]: @Turbo87, sorry but I didn't understand what you just said :(

Tests for this should be similar to what we already have, we just need to overwrite the property and them check the stack trace to make sure it does not include that `_super` call. Basically you've got to ensure the second example you posted on [this issue](https://github.com/chaijs/chai/issues/659) won't happen.

Comment (Turbo87) [inline lib/chai/utils/addProperty.js]: damn autocorrect... that was "not sure I understand what you meant" 😉

**Comment by Turbo87** [comment]
@lucasfcosta I've added a few tests to verify that the stack traces work correctly when overwriting properties and methods

File: test/utilities.js [hunk 4]
```diff
@@ -320,6 +320,60 @@ describe('utilities', function () {
...
+    it('calling _super has correct stack trace', function() {
+      try {
+        expect(5).to.be.four();
+        expect(false, 'should not get here because error thrown').to.be.ok;
+      } catch (err) {
+        // not all browsers support err.stack
+        // Phantom does not include function names for getter exec
+        if ('undefined' !== typeof err.stack && 'undefined' !== typeof Error.captureStackTrace) {
+          expect(err.stack).to.include('utilities.js');
+          expect(err.stack).to.not.include('overwriteProperty');
```
Comment (lucasfcosta) [inline test/utilities.js]: I believe you should be checking if it does not include `overwriteMethod` instead of `overwriteProperty` here, shouldn't you?

File: test/utilities.js [hunk 5]
```diff
@@ -320,6 +320,60 @@ describe('utilities', function () {
...
+    it('overwritten behavior has correct stack trace', function() {
+      try {
+        expect('five').to.be.four();
+        expect(false, 'should not get here because error thrown').to.be.ok;
+      } catch (err) {
+        // not all browsers support err.stack
+        // Phantom does not include function names for getter exec
+        if ('undefined' !== typeof err.stack && 'undefined' !== typeof Error.captureStackTrace) {
+          expect(err.stack).to.include('utilities.js');
+          expect(err.stack).to.not.include('overwriteProperty');
```
Comment (lucasfcosta) [inline test/utilities.js]: The same applies to this line.
(`overwriteMethod` instead of `overwriteProperty`)

**Comment by lucasfcosta** [comment]
Great job @Turbo87, I just think you accidentally looked for `overwriteProperty` on the stack-trace for `overwriteMethod` tests.

File: test/utilities.js (hunk 5 above)
Comment (Turbo87) [inline test/utilities.js]: whoops, copy-paste issue. sorry!

**Comment by Turbo87** [comment]
@lucasfcosta fixed

File: test/utilities.js (hunk 4 above)
Comment (lucasfcosta) [inline test/utilities.js]: hahaha, np, happens to everyone sometimes :laughing:

**Comment by lucasfcosta** [comment]
This LGTM!
Nice job!
